# Generated by Django 3.2.23 on 2023-11-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='costumer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='costumer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='instruments',
        ),
    ]
